// AStar.h: interface for the CAStar class.
//
//////////////////////////////////////////////////////////////////////

#if !defined(AFX_ASTARTILEDEFINE_H__188F22E5_30B3_11D4_83C9_0080C8F6368B__INCLUDED_)
#define AFX_ASTARTILEDEFINE_H__188F22E5_30B3_11D4_83C9_0080C8F6368B__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
//	Walkable map tile
//	可走地圖單元
#define ASTAR_TILE_FREE		0x00

#define ASTAR_TILE_GENERAL	0x01
#define ASTAR_TILE_WATER 0x02
#define ASTAR_TILE_CREATURE	0x04
#define ASTAR_TILE_FLYINGCREATURE 0x08
#define ASTAR_TILE_WATERCREATURE 0x10
#define ASTAR_TILE_FLYINGGENERAL 0x20
#define ASTAR_TILE_BOUNDARY 0x40
#define ASTAR_TILE_DYNGENERAL 0x80
#define ASTAR_TILE_STATICBLOCKED (ASTAR_TILE_GENERAL|ASTAR_TILE_WATER|ASTAR_TILE_DYNGENERAL)//The block info that will never change
#define ASTAR_TILE_FLYINGSTATICBLOCKED (ASTAR_TILE_FLYINGGENERAL)

#define ASTAR_TILE_GRACEBLOCK (ASTAR_TILE_CREATURE|ASTAR_TILE_BOUNDARY)
#define ASTAR_TILE_GROUNDBLOCK (ASTAR_TILE_STATICBLOCKED|ASTAR_TILE_CREATURE|ASTAR_TILE_BOUNDARY)
#define ASTAR_TILE_AIRBLOCK (ASTAR_TILE_FLYINGCREATURE|ASTAR_TILE_FLYINGSTATICBLOCKED|ASTAR_TILE_BOUNDARY)
#define ASTAR_TILE_UNDERGROUNDBLOCK (ASTAR_TILE_GENERAL|ASTAR_TILE_BOUNDARY)

#define ASTAR_TILE_PASSPORT ASTAR_TILE_CREATURE //For temp use in MapEditor2


#endif // !defined(AFX_ASTARTILEDEFINE_H__188F22E5_30B3_11D4_83C9_0080C8F6368B__INCLUDED_)

