;////////////////////////////////////////////////////////////////////////////////////////////////
;OpenRouter
[Provider]
name=OpenRouter
endpoint=https://openrouter.ai/api/v1/chat/completions
apiFormat=OpenRouter

[Api]
name=gemini-3.1-pro-preview(openrouter)
model=google/gemini-3.1-pro-preview
provider=OpenRouter
maxToken=32000
priceInputToken=2.0
priceCacheRead=0.2
priceOutputToken=12.0
purpose=MajorChat
contextCapacity=200000

[Api]
name=claude-4.5(openrouter)
model=anthropic/claude-sonnet-4.5
provider=OpenRouter
maxToken=32000
priceInputToken=3.0
priceCacheRead=0.3
priceCacheWrite=3.75
priceOutputToken=15.0
purpose=MajorChat
cacheControl=Anthropic
contextCapacity=160000

[Api]
name=GPT-5(openrouter)
desc=GPT-5 via OpenRouter
model=openai/gpt-5
provider=OpenRouter
maxToken=32000
priceInputToken=1.25
priceCacheRead=0.125
priceOutputToken=10.0
purpose=MajorChat
contextCapacity=160000

[Api]
name=llama-3.3-70b(openrouter)
model=meta-llama/llama-3.3-70b-instruct
provider=OpenRouter
maxToken=65536
priceInputToken=0.0
priceOutputToken=0.0
purpose=MinorChat
contextCapacity=60000

;////////////////////////////////////////////////////////////////////////////////////////////////
;//OpenAI
[Provider]
name=OpenAI
endpoint=https://api.openai.com/v1/chat/completions
apiFormat=OpenAI

[Api]
name=gpt-5.4
model=gpt-5.4
provider=OpenAI
maxToken=64000
priceInputToken=2.5
priceCacheRead=0.25
priceOutputToken=15.0
purpose=MajorChat
contextCapacity=160000

[Api]
name=gpt-5.4-nano
model=gpt-5.4-nano
provider=OpenAI
maxToken=64000
priceInputToken=0.2
priceCacheRead=0.02
priceOutputToken=1.25
purpose=MinorChat
contextCapacity=60000

;////////////////////////////////////////////////////////////////////////////////////////////////
;//Anthropic
[Provider]
name=Anthropic
endpoint=https://api.anthropic.com/v1/messages
apiFormat=Anthropic

[Api]
name=claude sonnet 4.6
model=claude-sonnet-4-6
provider=Anthropic
priceInputToken=3.0
priceCacheRead=0.3
priceCacheWrite=3.75
priceOutputToken=15.0
purpose=MajorChat
contextCapacity=160000

[Api]
name=claude opus 4.6
model=claude-opus-4-6
provider=Anthropic
priceInputToken=5.0
priceCacheRead=0.5
priceCacheWrite=6.25
priceOutputToken=25.0
purpose=MajorChat
contextCapacity=160000

[Api]
name=claude haiku 4.5
model=claude-haiku-4-5-20251001
provider=Anthropic
priceInputToken=1.0
priceCacheRead=0.1
priceCacheWrite=1.25
priceOutputToken=5.0
purpose=MinorChat
contextCapacity=60000

;////////////////////////////////////////////////////////////////////////////////////////////////
;//Google AI
[Provider]
name=Google AI
endpoint=https://generativelanguage.googleapis.com/v1beta/openai/chat/completions
apiFormat=OpenAI

[Api]
name=gemini-3.1-pro-preview
model=gemini-3.1-pro-preview
provider=Google AI
maxToken=64000
priceInputToken=2
priceCacheRead=0.2
priceOutputToken=12
purpose=MajorChat
contextCapacity=160000

[Api]
name=gemini-3.1-flash-lite-preview
model=gemini-3.1-flash-lite-preview
provider=Google AI
maxToken=64000
priceInputToken=0.25
priceCacheRead=0.025
priceOutputToken=1.5
purpose=MinorChat
contextCapacity=60000


;////////////////////////////////////////////////////////////////////////////////////////////////
;//GLM
[Provider]
name=GLM
endpoint=https://open.bigmodel.cn/api/coding/paas/v4/chat/completions
apiFormat=GLM

[Api]
name=GLM-4.7
model=glm-4.7
provider=GLM
maxToken=131072
priceInputToken=0.2899
priceCacheRead=0.072
priceOutputToken=1.14
purpose=MajorChat,MinorChat
contextCapacity=100000

[Api]
name=GLM-5
model=glm-5
provider=GLM
maxToken=131072
priceInputToken=0.57
priceCacheRead=0.14
priceOutputToken=2.57
purpose=MajorChat
contextCapacity=120000

;////////////////////////////////////////////////////////////////////////////////////////////////
;//Moonshot AI
[Provider]
name=Moonshot AI
endpoint=https://api.moonshot.cn/v1/chat/completions
apiFormat=Kimi

[Api]
name=kimi-k2
model=kimi-k2-0905-preview
provider=Moonshot AI
maxToken=262144
priceInputToken=0.5797
priceCacheRead=0.14
priceOutputToken=2.3188
purpose=MajorChat,MinorChat
contextCapacity=80000

[Api]
name=kimi-k2.5
model=kimi-k2.5
provider=Moonshot AI
maxToken=262144
priceInputToken=0.5797
priceCacheRead=0.1
priceOutputToken=3.0435
purpose=MajorChat
contextCapacity=120000

;///////////////////////
[Provider]
name=DeepSeek
endpoint=https://api.deepseek.com/chat/completions
apiFormat=DeepSeek

[Api]
name=DeepSeek4 pro
model=deepseek-v4-pro
maxToken=32000
priceInputToken=0.4275
priceCacheRead=0.00357
priceOutputToken=0.83
purpose=MajorChat
thinkingMode=Disable
provider=DeepSeek

[Api]
name=DeepSeek4 pro ( thinking )
model=deepseek-v4-pro
maxToken=32000
priceInputToken=0.4275
priceCacheRead=0.00357
priceOutputToken=0.83
purpose=MajorChat
provider=DeepSeek

[Api]
name=DeepSeek4 flash
model=deepseek-v4-flash
maxToken=32000
priceInputToken=0.14
priceCacheRead=0.003
priceOutputToken=0.28
purpose=MinorChat
thinkingMode=Disable
provider=DeepSeek

;////////////////////////////////////////////////////////////////////////////////////////////////
;//OFox AI (Anthropic API)
[Provider]
name=OFox AI(Anthropic)
endpoint=https://api.ofox.ai/anthropic/v1/messages
apiFormat=Anthropic

[Api]
name=Claude Sonnet 4.6(OFox AI)
model=anthropic/claude-sonnet-4.6
maxToken=32000
priceInputToken=3.0
priceCacheRead=0.3
priceCacheWrite=3.75
priceOutputToken=15.0
purpose=MajorChat
provider=OFox AI(Anthropic)
contextCapacity=160000

;////////////////////////////////////////////////////////////////////////////////////////////////
;//OFox AI(OpenAI API)
[Provider]
name=OFox AI(OpenAI)
endpoint=https://api.ofox.ai/v1/chat/completions
apiFormat=OpenAI

[Api]
name=gpt-5.4(OFox AI)
model=openai/gpt-5.4
maxToken=32000
priceInputToken=2.5
priceCacheRead=0.25
priceOutputToken=15.0
purpose=MajorChat
provider=OFox AI(OpenAI)
contextCapacity=160000

;////////////////////////////////////////////////////////////////////////////////////////////////
;//OFox AI
[Provider]
name=OFox AI(Gemini)
endpoint=https://api.ofox.ai/gemini/v1beta
apiFormat=Gemini

[Api]
name=Gemini 3.1 pro(OFox AI)
model=google/gemini-3.1-pro-preview
maxToken=32000
priceInputToken=2
priceCacheRead=0.2
priceOutputToken=12.0
purpose=MajorChat
provider=OFox AI(Gemini)
contextCapacity=200000
