; 将此文件放在程序目录下，文件名为 llmext.ini
; 扩展的LLM Provider 和 API 配置文件

; ============================================
; Provider 配置部分
; ============================================

[Provider]
name=Ubisoft LiteLLM
desc=Ubisoft LiteLLM
url=https://litellm.ubisoft.org/
endpoint=https://litellm.ubisoft.org/v1/chat/completions
key=

[Provider]
name=OFox AI
desc=OFox AI
url=https://api.ofox.ai
endpoint=https://api.ofox.ai/anthropic/v1/messages
key=sk-of-jkuoklYPGIFbtozJMacsTLCEYlFXKsIUkOuHXeVCytmnYCfSbZhwsmtuBCezAeWl


; ============================================
; API 配置部分
; ============================================

[Api]
name=Claude Sonnet 4.6(Ubisoft)
desc=Claude Sonnet 4.6 via Ubisoft Service
model=claude-sonnet-4-6
rule=chatrules_usingtools
maxToken=0
priceInputToken=3.0
priceOutputToken=15.0
purpose=MajorChat
provider=Ubisoft LiteLLM
cacheControl=Anthropic
apiFormat=OpenAI
tools=ReplaceInFile,FindSymbolDefine,FindInFiles,ReadFile
only=


[Api]
name=Claude Sonnet 4.6(OFox AI)
desc=Claude Sonnet 4.6 via OFox AI
model=claude-sonnet-4-6
rule=chatrules_usingtools
maxToken=32000
priceInputToken=3.0
priceOutputToken=15.0
purpose=MajorChat
provider=OFox AI
cacheControl=Anthropic
apiFormat=Anthropic
tools=ReplaceInFile,FindSymbolDefine,FindInFiles,ReadFile
only=

