#pragma once

#define FVFEX_MASK(v) (((FVFEx)0x1)<<(v))

#define FVFEX_XYZNORMAL_MAXSET 2

#define FVFEX_NULL					0x0

#define FVFEX_XYZ0              FVFEX_MASK(0)
#define FVFEX_XYZ1              FVFEX_MASK(1)
#define FVFEX_XYZ(n)			FVFEX_MASK(0+n)

#define FVFEX_XYZRHW		FVFEX_MASK(2)

#define FVFEX_XYZW0			FVFEX_MASK(3)
#define FVFEX_XYZW1			FVFEX_MASK(4)
#define FVFEX_XYZW(n)		FVFEX_MASK(3+n)

#define FVFEX_NORMAL0		FVFEX_MASK(5)
#define FVFEX_NORMAL1		FVFEX_MASK(6)
#define FVFEX_NORMAL(n)	FVFEX_MASK(5+n)

#define FVFEX_BINORMAL	FVFEX_MASK(7)
#define FVFEX_TANGENT			FVFEX_MASK(8)

#define FVFEX_PSIZE				FVFEX_MASK(9)

#define FVFEX_DIFFUSE			FVFEX_MASK(10)

#define FVFEX_SPECULAR		FVFEX_MASK(11)

//For terrain usage
#define FVFEX_TRRN_POS			FVFEX_MASK(12)
#define FVFEX_TRRN_TEX00		FVFEX_MASK(13)
#define FVFEX_TRRN_TEX01		FVFEX_MASK(14)
#define FVFEX_TRRN_TEX02		FVFEX_MASK(15)
#define FVFEX_TRRN_TEX03		FVFEX_MASK(16)
#define FVFEX_TRRN_TEX04		FVFEX_MASK(17)
#define FVFEX_TRRN_TEX05		FVFEX_MASK(18)
#define FVFEX_TRRN_NORMAL		FVFEX_MASK(19)


#define FVFEX_TEX_MAXSET (8)
#define FVFEX_FLAG_TEX0		FVFEX_MASK(20)
#define FVFEX_FLAG_TEX1		FVFEX_MASK(21)
#define FVFEX_FLAG_TEX2		FVFEX_MASK(22)
#define FVFEX_FLAG_TEX3		FVFEX_MASK(23)
#define FVFEX_FLAG_TEX4		FVFEX_MASK(24)
#define FVFEX_FLAG_TEX5		FVFEX_MASK(25)
#define FVFEX_FLAG_TEX6		FVFEX_MASK(26)
#define FVFEX_FLAG_TEX7		FVFEX_MASK(27)
#define FVFEX_FLAG_TEX(n)		FVFEX_MASK(20+n)

#define FVFEX_WEIGHT_MAXSET 4
#define FVFEX_WEIGHT0			FVFEX_MASK(28)
#define FVFEX_WEIGHT01			FVFEX_MASK(29)
#define FVFEX_WEIGHT012		FVFEX_MASK(30)
#define FVFEX_WEIGHT0123		FVFEX_MASK(31)
#define FVFEX_WEIGHT(n)			FVFEX_MASK(27+n) //n: 1~4

#define FVFEX_BONEINDICE0		FVFEX_MASK(32)
#define FVFEX_BONEINDICE1		FVFEX_MASK(33)
#define FVFEX_BONEINDICE(n)		FVFEX_MASK(32+n)

//三维贴图坐标
#define FVFEX_FLAG_VOX0		FVFEX_MASK(34)
#define FVFEX_FLAG_VOX1		FVFEX_MASK(35)
#define FVFEX_FLAG_VOX2		FVFEX_MASK(36)
#define FVFEX_FLAG_VOX3		FVFEX_MASK(37)
#define FVFEX_FLAG_VOX4		FVFEX_MASK(38)
#define FVFEX_FLAG_VOX5		FVFEX_MASK(39)
#define FVFEX_FLAG_VOX6		FVFEX_MASK(40)
#define FVFEX_FLAG_VOX7		FVFEX_MASK(41)
#define FVFEX_FLAG_VOX(n)		FVFEX_MASK(34+n)

//四维贴图坐标
#define FVFEX_FLAG_QUX0		FVFEX_MASK(42)
#define FVFEX_FLAG_QUX1		FVFEX_MASK(43)
#define FVFEX_FLAG_QUX2		FVFEX_MASK(44)
#define FVFEX_FLAG_QUX3		FVFEX_MASK(45)
#define FVFEX_FLAG_QUX(n)	FVFEX_MASK(42+n)

//一些精简的顶点格式
#define FVFEX_COMPACT_POS		FVFEX_MASK(46)
#define FVFEX_COMPACT_NORMAL FVFEX_MASK(47)
#define FVFEX_COMPACT_BINORMAL FVFEX_MASK(52)

//Vege使用的顶点格式
#define FVFEX_VEGE_POS					FVFEX_COMPACT_POS
#define FVFEX_VEGE_NORMAL			FVFEX_COMPACT_NORMAL
#define FVFEX_VEGE_TEX					FVFEX_MASK(48)
#define FVFEX_VEGE_COL					FVFEX_MASK(49)
#define FVFEX_VEGE_GEOM				FVFEX_MASK(50)
#define FVFEX_VEGE_PARAM			FVFEX_MASK(51)
#define FVFEX_VEGE_BINORMAL		FVFEX_COMPACT_BINORMAL

//浮点颜色
#define FVFEX_DIFFUSE_F			FVFEX_MASK(55)


typedef unsigned __int64 FVFEx;

#define FVFEx_Mod(fvf,fvfToAdd,fvfToRemove)\
	fvf=((fvf)|((FVFEx)(fvfToAdd)))&(~(FVFEx)(fvfToRemove))
