//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Proj_GuiLib.rc
//
#define IDCANCEL2                       3
#define ID_SELNONE                      3
#define IDC_NEWANDADD                   3
#define ID_CHECKIN                      3
#define ID_CHECKOUT                     4
#define ID_GET                          5
#define ID_SELECTALL                    6
#define ID_DESELECTALL                  7
#define IDD_MESHMAIN                    102
#define IDD_BONEANIM                    103
#define IDC_POINTER_COPY                105
#define IDC_NODROP                      106
#define IDI_LOGREPORTFLASH              132
#define IDD_DIALOG_SPTFOREST            136
#define IDB_IMAGE_SPTLIB                138
#define IDI_RESTREE_MESH                1000
#define IDC_BUTTON1                     1000
#define IDC_STARTFRAME                  1000
#define IDC_STARTTICK                   1000
#define IDC_REMOVESURF                  1000
#define IDC_ADDFULLPTTN                 1000
#define IDC_SAVE                        1000
#define IDC_REMOVEUVCHANNEL             1000
#define IDC_CONTENTTREE                 1000
#define IDC_RELOADPROTOLIB              1000
#define IDC_BTEDIT                      1000
#define IDC_BUTTON_CLEAR                1000
#define IDC_BTMODIFY                    1000
#define IDC_BUTTON_RESET_BL             1000
#define IDC_ADDCP                       1000
#define IDC_TEXANCHOR                   1000
#define IDC_SSCBTN                      1000
#define IDC_BUTTON_RESETXF              1000
#define IDC_BUTTON_FILEBROWSE           1000
#define IDC_BUTTON_SELECTALL            1000
#define IDI_RESTREE_BONES               1001
#define IDC_BONEANIMANCHOR              1001
#define IDC_CLEARPTTN                   1001
#define IDC_LOAD                        1001
#define IDC_GUTTER                      1001
#define IDC_BUTTON_CANCLE               1001
#define IDC_SHEETANCHOR                 1001
#define IDC_AUTOREPAIRGUID              1001
#define IDC_REPAIRGUID                  1001
#define IDI_RESTREE_XFORM               1002
#define IDC_MESHANCHOR                  1002
#define IDC_ENDTICK                     1002
#define IDC_SAVEAS                      1002
#define IDC_STRETCH                     1002
#define IDC_BUTTON_OK                   1002
#define IDC_FORCERELOADPROTOLIB         1002
#define IDI_RESTREE_UNKNOWN             1003
#define IDC_LOAD2                       1003
#define IDC_NEW                         1003
#define IDC_ALPHA_SLIDER                1003
#define IDI_RESTREE_NODE                1004
#define IDC_ANIMPIECELIST               1004
#define IDC_WIDTH                       1004
#define IDC_RADIO_RGB_R                 1004
#define IDC_NEW2                        1004
#define IDC_DELETE                      1004
#define IDR_RESTREEBAR                  1005
#define IDC_ANIMEVENTLIST               1005
#define IDC_HEIGHT                      1005
#define IDR_TOOLBAR1                    1006
#define IDC_BUTTON2                     1006
#define IDC_PREVTEX                     1006
#define IDC_SAVETRRNMAP                 1006
#define IDC_MAKEUVATLAS                 1006
#define IDC_RESIDE                      1006
#define IDC_RESSLECTANCHOR              1006
#define IDC_BT_SSC                      1006
#define IDC_BT_CHECKOUT                 1006
#define IDC_ADDWATCH                    1006
#define IDC_RADIO_HSB_H                 1006
#define IDC_BUTTON_DESELECTALL          1006
#define IDB_BITMAP1                     1007
#define IDC_ANIMINFO                    1007
#define IDC_NEXTTEX                     1007
#define IDC_ASSIGNATLASPARAM            1007
#define IDC_RADIO_HSB_B                 1007
#define IDC_LIST1                       1008
#define IDC_APBONELIST                  1008
#define IDC_TABSLOT                     1008
#define IDC_PTTNSETLIST                 1008
#define IDC_LIST                        1008
#define IDC_WBRUSHLIST                  1008
#define IDC_STATIC_HSB_H                1008
#define IDC_CTRL                        1008
#define IDC_ANIMTREEGRID                1008
#define IDC_LIST_SHOREBRUSH             1008
#define IDC_LIST_MAPREGID               1008
#define IDI_RESTREE_FOLDER              1009
#define IDC_EDIT                        1009
#define IDC_STATIC_HSB_S                1009
#define IDI_RESTREE_FILE                1010
#define IDC_PROMPT                      1010
#define IDC_STATIC_HSB_S2               1010
#define IDR_TOOLBAREXT                  1011
#define IDC_STARTKEY                    1011
#define IDC_RADIO_RGB_G                 1011
#define IDI_LOGREPORTFLASH1             1011
#define IDC_ENDKEY                      1012
#define IDR_TOOLBAREXT1                 1012
#define IDR_ASSETCLASSBUTTON            1012
#define IDR_ASSETCLASSPROPERTY          1012
#define IDC_RADIO_HSB_S                 1012
#define IDI_LOGREPORTFLASH2             1012
#define IDC_MTRLANCHOR                  1013
#define IDC_COLOR_SHOW                  1013
#define IDB_BITMAP2                     1014
#define IDB_RESTREEICON                 1014
#define IDC_MTRLGRIDSLOT                1014
#define ID_SAVESPTLIB                   1014
#define IDD_ANCHORPOPUP                 1015
#define IDC_MTRLANCHOR2                 1015
#define IDC_MESHANCHOR_MTRLSAMPLE       1015
#define IDC_TREE_SPTLIB                 1015
#define IDC_COLOR_PICKER                1015
#define IDC_WND                         1015
#define IDR_RESTREEMENU                 1016
#define IDC_VIEWOPT_MESHCOMBO           1016
#define IDC_BT_PATHLIB                  1016
#define IDC_EDIT_VALIDPIXEL             1016
#define IDD_INPUTDLG                    1017
#define IDC_SURFCOMBO                   1017
#define IDC_EDIT_SPTLIBPATH             1017
#define IDC_EDIT_DENSITYPIXEL           1017
#define IDC_MTRLGRIDSLOT2               1017
#define IDC_VSDLGSLOT                   1017
#define IDD_MTRLMAIN                    1018
#define IDC_FRAMECOMBO                  1018
#define IDC_CHECK3                      1018
#define IDC_CHECK_SAMPLES               1018
#define IDC_CHECK_SCALE                 1018
#define IDC_CHECK_PSHOWSAMP             1018
#define IDC_CHECK_TREPAIR_VEGETABLE     1018
#define IDB_RGBUTTONS                   1019
#define IDC_TANGENTCHECK                1019
#define IDC_CHECK_SEGMENT               1019
#define IDD_MESHCONTENT                 1020
#define IDC_MESHCONTENTSLOT             1020
#define IDC_PERPIXELLIGHTCHECK          1021
#define IDB_IMAGEBLANKMARK              1021
#define IDD_TRRNBRUSHLIBDLG             1022
#define IDB_IMAGEERRORMARK              1022
#define IDD_TBL_TEXSET                  1023
#define IDC_PTTNCTRL                    1024
#define IDB_PTTNSAMPLE                  1024
#define IDC_TEXLIST                     1025
#define IDD_TBL_BRUSH                   1025
#define IDC_TEXSETLIST                  1025
#define IDC_CHECK_BRANCH                1025
#define IDC_TEXCTRL                     1026
#define IDC_CHECK_FROND                 1026
#define IDC_ADDTEX                      1027
#define IDC_CHECK_LEAVE                 1027
#define IDC_TEXCTRL2                    1027
#define IDC_REMOVETEX                   1028
#define IDC_BUTTON_REPAIR               1028
#define IDC_CLEARTEX                    1029
#define IDR_PTTNCORNER                  1029
#define IDC_METERCOMBO                  1030
#define IDR_PTTNFRAME                   1030
#define IDC_LENSLOT                     1030
#define IDC_LOW                         1030
#define IDC_BRUSHLIST                   1031
#define IDC_GROUPCOMBO                  1031
#define IDR_PTTNFRAME2                  1031
#define IDC_MEDIUM                      1031
#define IDC_SPIN_TRANS_OFFX             1031
#define IDC_COMBO1                      1031
#define IDC_LIB                         1031
#define IDC_RADIUSCOMBO                 1031
#define IDC_UNITWIDTH                   1031
#define IDC_TEXSETCOMBO                 1032
#define IDD_PTTNPOP                     1032
#define IDC_HI                          1032
#define IDC_SPIN_TRANS_OFFZ             1032
#define IDC_FUNC                        1032
#define IDC_PTTNSETCOMBO                1033
#define IDC_SPIN_TRANS_ABX              1033
#define IDC_FUNC2                       1033
#define IDC_TYPE                        1033
#define IDC_UNITHEIGHT                  1033
#define IDC_TEXSETSLOT                  1034
#define IDD_CHANGEBRUSHIDDLG            1034
#define IDC_SPIN_TRANS_ABZ              1034
#define IDC_PTTNSETSLOT                 1035
#define IDC_SPIN_TRANS_OFFXYZ           1035
#define IDC_GROUPCOMBO2                 1036
#define IDC_PAINTTRRN                   1036
#define IDC_PAINTTRRNCURSOR             1036
#define IDC_SPIN_TRANS_ABXYZ            1036
#define IDC_REPEATCOMBO                 1037
#define IDD_BAKEPROGRESSDLG             1037
#define IDC_MONTHCALENDAR1              1037
#define IDC_BRUSHIDSTATIC               1038
#define IDD_UVATLASMAKEDLG              1038
#define IDC_PROGRESS1                   1038
#define IDC_PROGRESS_BAKELIB            1038
#define IDC_TBL_FILEPATH                1039
#define IDD_EDITPANEL_ACL               1039
#define IDC_LEVELCOMBO                  1040
#define IDD_EDITPANEL_AP                1040
#define IDC_NORMAL                      1040
#define IDC_BUTTON_BAKESTART            1040
#define IDC_TEXDESC                     1041
#define IDB_SELECTITEM                  1041
#define IDC_STATIC_BAKEINFO             1041
#define IDC_FALLBACKCOMBO               1041
#define IDC_COPYDRAGING                 1042
#define IDC_COPYPATH                    1042
#define IDC_COMBO                       1043
#define IDC_BUTTON_TREPAIR              1043
#define IDC_STATIC2                     1044
#define IDC_SPIN_PROBELEN               1044
#define IDC_CHANGEBRID                  1045
#define IDD_ASCFGDLG                    1045
#define IDD_MFADLG                      1045
#define IDC_SPIN_PROBEHEIGHT            1045
#define IDC_BRUSHCOMBO                  1046
#define IDC_EDIT_PROBEGRID              1046
#define IDC_TEXSLOT                     1047
#define IDC_SPIN_PROBEGRID              1047
#define IDC_PTTNSLOT                    1048
#define IDC_PAINTTRRNBTN                1049
#define IDC_PAINTBASETRRNBTN            1050
#define IDC_PROGRESSMAIN                1051
#define IDC_PAINTHEIGHTMAPBTN           1052
#define IDC_TITLE                       1052
#define IDC_TITLEMAIN                   1052
#define IDC_LOADHEIGHTMAP               1053
#define IDC_PROGRESSSUB                 1053
#define IDC_TITLE2                      1053
#define IDC_SYNC                        1053
#define IDC_PAINTHOLEBTN                1054
#define IDC_TITLESUB                    1054
#define IDC_CLEARHOLEBTN                1055
#define IDC_DUMPEDIT                    1055
#define IDC_MOVEDRAGING                 1055
#define IDC_VIEWPORT                    1056
#define IDC_UVCHANNEL                   1059
#define IDC_DESC                        1060
#define IDC_DRAGING                     1060
#define IDC_CUTDRAGING                  1060
#define IDC_EDIT1                       1061
#define IDC_DUMMYLIST                   1061
#define IDC_DUMMIESLIST                 1061
#define IDC_EDIT_SPEEDTREEINFO          1061
#define IDC_EDIT_INNERRADIUS            1061
#define IDC_EDIT_MESSAGE                1061
#define IDC_EDIT_BAKEINFO               1061
#define IDC_EDIT_MINHEIGHT              1061
#define IDC_EDIT_BRUSHSIZE              1061
#define IDC_EDIT_DENSITY                1061
#define IDC_EDIT_RGB_R                  1061
#define IDC_EDIT_TRANS_OFFX             1061
#define IDC_EDIT_SNAPMOVE               1061
#define IDC_EDIT_PROBELEN               1061
#define IDC_EDIT_CELLSIZE               1061
#define IDC_EDIT_OPMAPRANGE             1061
#define IDC_SLIDER1                     1062
#define IDC_SLIDER_INNERRADIUS          1062
#define IDC_SLIDER_MINHEIGHT            1062
#define IDC_SLIDER_BRUSHSIZE            1062
#define IDC_SLIDER_DENSITY              1062
#define IDC_EDIT_RGB_G                  1062
#define IDC_EDIT_TRANS_ABX              1062
#define IDC_SLIDER_SHAPEWINNER          1062
#define IDC_EDIT_CELLHEIGHT             1062
#define IDC_ANIMCONTRLBAR               1063
#define IDC_EDIT_OUTTERRADIUS           1063
#define IDC_EDIT_MAXHEIGHT              1063
#define IDC_EDIT_RGB_B                  1063
#define IDC_DUMMYPROPERTY               1064
#define IDC_SLIDER_OUTTERRADIUS         1064
#define IDC_SLIDER_MAXHEIGHT            1064
#define IDC_EDIT_HSB_H                  1064
#define IDC_EDIT_HEIGHT                 1065
#define IDC_EDIT_HSB_S                  1065
#define IDC_EDIT_PAINTSPEED             1065
#define IDC_VIEWPROPERTIES              1066
#define IDC_SLIDER_HEIGHT               1066
#define IDC_EDIT_RGB_B2                 1066
#define IDC_EDIT_HSB_B                  1066
#define IDC_SLIDER_PAINTSPEED           1066
#define IDC_INFO                        1067
#define IDC_INFO2                       1067
#define IDC_EDIT_HARDNESS               1067
#define IDC_EDIT_HEX                    1067
#define IDC_SLIDER_HARDNESS             1068
#define IDC_EDIT_SCALE_MIN              1068
#define IDC_EDIT3                       1069
#define IDC_EDIT_SCALE_MAX              1069
#define IDC_EDIT_SEG                    1069
#define IDC_EDIT_SEGID                  1069
#define IDC_EDIT_TRANS_OFFZ             1069
#define IDC_EDIT_SNAPSCALE              1069
#define IDC_EDIT_PROBEHEIGHT            1069
#define IDC_EDIT_SHAPEWOUTTER           1069
#define IDC_EDIT_TRANS_ABZ              1070
#define IDC_EDIT_SHORE_STARTTIME        1070
#define IDC_EDIT_TRANS_OFFXYZ           1071
#define IDC_BUTTON3                     1072
#define IDC_BT_BAKESPTLIB               1072
#define IDC_BT_GETLATESTVERSION         1072
#define IDC_EDIT_TRANS_ABXYZ            1072
#define IDC_BUTTON_GENBB                1072
#define IDC_TREE2                       1073
#define IDB_PAUSE                       1074
#define IDC_CHECK1                      1074
#define IDC_CHECK_SHOWOBB               1074
#define IDC_CHECK_FULLWEIGHT            1074
#define IDC_CHECK_PAINTVEGETABLE        1074
#define IDC_CHECK_SHOWDUMMIES           1074
#define IDC_CHECK_PAINT                 1074
#define IDC_CHECK_MOVE                  1074
#define IDC_CHECK_SNAPMOVE              1074
#define IDC_CHECK_TREPAIR_TREE          1074
#define IDC_CHECK_ADDPROBE              1074
#define IDC_CHECK_ETPROBECREATE         1074
#define IDC_CHECK_SHORESHOREWIRE        1074
#define IDC_BASHOWSTD                   1074
#define IDC_CHECK_MAPATTRWIREFRAME      1074
#define IDC_RANDOMROTATE                1074
#define IDB_PLAY                        1075
#define IDC_CURPROJECT                  1075
#define IDC_CHECK_REMOVEGETABLE2        1075
#define IDC_CHECK4                      1075
#define IDC_CHECK_SHOWLEAFHOOK          1075
#define IDC_REIDEONGROUND               1075
#define IDC_RESIDEONGROUND              1075
#define IDC_CONTENT                     1076
#define IDC_CHECK_HEIGHTSET             1076
#define IDC_AUTOALIGN                   1076
#define IDB_STOP                        1077
#define IDC_REPLACEMODE                 1077
#define IDC_CHECK_HEIGHTSET2            1077
#define IDB_INDICATOR                   1078
#define IDC_MOUSEINFO                   1078
#define IDB_FILESAVE                    1079
#define IDC_FILENAME                    1079
#define IDD_DUMMIESPANEL                1080
#define IDB_RESTREEICON2                1080
#define IDD_EDITPANEL_ASSET             1081
#define IDD_EDITPANEL_ENTITY            1081
#define IDD_EDITPANEL_ACL1              1082
#define IDD_SLIDECONTAINER              1082
#define IDC_MESHSELECTOR                1082
#define IDC_MATERIALSELECTOR            1083
#define IDC_VIEWOPTIONGRP               1084
#define IDC_TREE1                       1085
#define IDC_TREE                        1085
#define IDC_TREE_VEGETABLELIB           1085
#define IDC_TREE_TREELIB                1085
#define IDC_SPEEDTREEANCHOR             1086
#define IDC_TREE3                       1086
#define IDC_PAGE                        1086
#define IDC_LIST_SPEEDWIND              1087
#define IDC_PAGE2                       1087
#define IDC_THUMBNAILLIST               1087
#define IDC_SPEEDWIND_PROP              1088
#define IDC_RESFILTERTREE               1089
#define IDC_DUMMYANCHOR                 1090
#define IDC_RESTYPESELECT               1090
#define IDB_ACLTREEICON                 1091
#define IDC_STATIC_SPTVIEW              1091
#define IDC_TV_LIBTREE                  1093
#define IDD_SSC_OPENDATABASE            1095
#define IDC_FSTPANEL_VIEW               1095
#define IDD_SSC_WORKFOLD                1096
#define IDC_LISTWINDS                   1097
#define IDC_CURSOR1                     1099
#define IDC_CURSORMOVE                  1099
#define IDC_WINDPROPS                   1099
#define IDB_BITMAP3                     1100
#define IDB_LOCK                        1100
#define IDC_SPTDRAWARG                  1100
#define IDD_SSC_CHOOSE                  1101
#define IDB_BITMAP4                     1102
#define IDB_QUESTION                    1102
#define IDC_BTADDTREE                   1102
#define IDB_PROJECT                     1103
#define IDD_RESOURCESELECTOR_DIALOG     1104
#define IDB_PRLTREEICON                 1104
#define IDD_EDITPANEL_ACL2              1105
#define IDD_EDITPANEL_PRL               1105
#define IDB_BITMAP5                     1105
#define IDB_SSCCHECKIN                  1106
#define IDD_EDITPANEL_PROTO             1106
#define IDC_BRPANEL_ANCHOR              1106
#define IDB_SSCCHECKOUT                 1107
#define IDD_PROTOSELECTDLG              1107
#define IDC_SPIN_INNERRADIUS            1107
#define IDB_SSCFORBID                   1108
#define IDD_ANCHORPOPUP1                1108
#define IDD_EDITPOPUP                   1108
#define IDC_SPIN_OUTTERRADIUS           1108
#define IDB_SSCEMPTY                    1109
#define IDD_EDITPOPUP1                  1109
#define IDD_STUBPOPUP                   1109
#define IDC_SPIN_HEIGHT                 1109
#define IDC_SPIN_PAINTSPEED             1109
#define IDB_PRLTREEICON1                1110
#define IDB_PROTOTREEICON               1110
#define IDD_SPEEDTREEPANEL              1110
#define IDC_SPIN_HARDNESS               1110
#define IDD_RESPANEL_SPG                1110
#define IDD_RESCHOOSEDLG                1111
#define IDC_CHECK_PRECISION             1111
#define IDC_COMBO_BRUSHLIST             1112
#define IDD_ACTOR_FOREST                1113
#define IDC_PAINT_TEXCTRL               1113
#define IDC_PAINT_PATTN                 1114
#define IDD_BRPANEL_RAISELOWER          1115
#define IDC_EDIT_SPEED                  1115
#define IDD_BRPANEL_TEXPAINTER          1116
#define IDC_SPIN_SPEED                  1116
#define IDC_SLIDER_SPEED                1117
#define IDB_BMREPORT                    1117
#define IDC_EDIT_RADIUS                 1118
#define IDB_CALLSTACK                   1118
#define IDC_SPIN_RADIUS                 1119
#define IDD_DIALOG_REPORTVIEW           1119
#define IDC_SLIDER_RADIUS               1120
#define IDD_DIALOG_REPORTRB             1120
#define IDD_DIALOG_MAPTOOLS             1121
#define IDC_STATIC_REPORTVIEW           1122
#define IDD_ACPANEL_MAP                 1122
#define IDC_COMBO_SYSTYPE               1123
#define IDD_TOOL_SSCMAP                 1123
#define IDD_DIALOG_TOOLBAKE             1124
#define IDC_TOOLAREAS                   1125
#define IDD_DIALOG_HEIGHMAP             1125
#define IDC_STATIC_DRAWAREA             1126
#define IDC_CURSORMOVE2                 1126
#define IDC_COMBO_TOOLS                 1127
#define IDC_CURSORLRMOVE                1127
#define IDC_STATIC_PANELTOOL            1128
#define IDC_CURSORULMOVE                1128
#define IDC_CURSOR_SL0MOVE              1129
#define IDC_CURSOR_SL0                  1129
#define IDC_PROGRESS_BAKE               1130
#define IDC_CURSORSL1MOVE               1130
#define IDD_PARTICLEFEATUREDLG          1131
#define IDC_STATIC_HMAPVIEW             1132
#define IDD_ACTOR_VEGETABLE             1132
#define IDC_SPIN_MINHEIGHT              1133
#define IDC_SPIN_MAXHEIGHT              1134
#define IDC_SPIN_SCALE_MIN              1134
#define IDB_BITMAP6                     1134
#define IDB_RESTEXICON                  1134
#define IDC_SPIN_SCALEHEIGHT            1135
#define IDC_SPIN2                       1135
#define IDC_SPIN_SCALE_MAX              1135
#define IDC_SPIN_TRANS_OFFY             1135
#define IDC_SPIN_PROBEWIDTH             1135
#define IDB_ASSETLIBICON                1135
#define IDC_SPIN_TRANS_ABY              1136
#define IDB_SYNCPROTO                   1136
#define IDC_WATERBRUSHGRID              1137
#define IDB_REFRESICON                  1137
#define IDB_SHADERLIBTREEICON           1138
#define IDD_DIALOG_STRLIB               1139
#define IDC_PAINTWATER                  1140
#define IDD_DIALOG_COLOR_PICKER         1141
#define IDD_COLOR_PICKER_DLG            1141
#define IDD_DIALOG_TRANSFORM            1142
#define IDC_CLEARWATER                  1143
#define IDD_DIALOG_TRANSSETTING         1143
#define IDC_SPIN_BRUSHSIZE              1144
#define IDD_DIALOG_TOOLMINMAP           1144
#define IDD_DIALOG1                     1145
#define IDD_DIALOG_BAKELIB              1145
#define IDC_COMBORENDERLVLV             1146
#define IDD_DIALOG_TOOLREPAIR           1146
#define IDD_GAMEDIALOG                  1147
#define IDC_IPADDRESS1                  1148
#define IDD_DIALOG_REPORTRB1            1148
#define IDD_DEBUG_CALLSTACK             1148
#define IDD_DEBUG_LOCALS                1149
#define IDD_DEBUG_WATCH                 1149
#define IDD_DEBUGVARDLG                 1150
#define IDD_PARTICLE_FEATURE_DLG        1151
#define IDD_BROKEN_LINE_DLG             1151
#define IDD_VALUESET_DLG                1151
#define IDC_PARTICLE_FEATURE_EDIT       1152
#define IDC_PAR_FEATURE_EDIT_MOUSE      1153
#define IDD_ACTOR_ETPROBE               1153
#define IDC_AIM                         1153
#define IDC_PAR_BROKENLINE_EDIT         1154
#define IDD_ACTOR_SHORE                 1154
#define IDC_POINTER_DRAWPROTO           1154
#define IDC_POINTER_DRAGPROTO           1154
#define IDC_CHECK2                      1155
#define IDC_CHECK_SHUV                  1155
#define IDC_CHECK_ROTATE                1155
#define IDC_CHECK_TREPAIR_WATER         1155
#define IDC_CHECK_PSHOWGRID             1155
#define IDD_ACTOR_RIDGE                 1155
#define IDD_DEBUG_CALLSTACK1            1156
#define IDD_DEBUG_OUTPUT                1156
#define IDC_SPTGLASSANCHOR              1156
#define IDD_PANEL_SPEEDTREE             1157
#define IDC_STATIC_SPGPORP              1157
#define IDC_STATIC_VEGETABLELIB         1158
#define IDD_GUIPANELCOMBO               1158
#define IDC_EDIT_SCALEMIN               1159
#define IDD_EDITPANEL_PATHES            1159
#define IDC_SPIN_SCALEMIN               1160
#define IDD_EDITPANEL_EL                1160
#define IDC_EDIT_SCALEMAX               1161
#define IDD_TEXPANEL                    1161
#define IDC_SPIN_SCALEMAX               1162
#define IDD_TEXPANEL1                   1162
#define IDD_SHEETPANEL                  1162
#define IDC_EDIT_WINDSTRENGTH           1163
#define IDD_BROKEN_LINE_DLG1            1163
#define IDD_MATEDITDLG                  1163
#define IDC_SLIDER_WINDSTRENGTH         1164
#define IDD_DIALOG_TOOLREPAIRTRRN       1164
#define IDC_EDIT_WINDSPEED              1165
#define IDD_DEBUG_LUAHELP               1165
#define IDC_SLIDER_WINDSPEED            1166
#define IDC_EDIT_WINDLEN                1167
#define IDC_SLIDER_WINDLEN              1168
#define IDC_EDIT_RENDERRANGE            1169
#define IDC_SLIDER_WINDLEN2             1170
#define IDC_SLIDER_RENDERRANGE          1170
#define IDC_EDIT2                       1170
#define IDC_EDIT_GAP                    1170
#define IDC_EDIT_TRANS_OFFY             1170
#define IDC_EDIT_SNAPROTATE             1170
#define IDC_EDIT_HEIGHTTRRN             1170
#define IDC_EDIT_PROBEWIDTH             1170
#define IDC_EDIT_AGENTHEIGHT            1170
#define IDC_SCROLLBAR1                  1171
#define IDC_EDIT_TRANS_ABY              1171
#define IDC_EDIT_AGENTRADIUS            1171
#define IDC_EDIT_HEIGHTTRRN2            1171
#define IDC_EDIT_AGENTMAXCLIMB          1172
#define IDC_ROOTPATH                    1173
#define IDC_EDIT_AGENTMAXSLOPE          1173
#define IDC_EDIT_MINREGION              1174
#define IDC_REMOVEFRAME                 1175
#define IDC_EDIT_MERGEREGION            1175
#define IDD_ACTOR_WATER                 1176
#define IDC_EDIT_MAXEDGELEN             1176
#define IDC_EDIT_MAXEDGEERROR           1177
#define IDC_EDIT_VERPERPOLY             1178
#define IDC_EDIT_SAMPDIST               1179
#define IDD_ACTOR_BAFFLE                1180
#define IDC_EDIT_MAXSAMPERROR           1180
#define IDC_DOUBLESIDENORMAL            1220
#define IDC_BT_GENLGHTUV                1221
#define IDC_CHANGE                      1222
#define IDC_CHECK_BAFFLECREATE          1223
#define IDD_EDITPANEL_TRRN              1224
#define IDC_ANIMTREEANCHOR              1225
#define IDC_CSMANCHOR                   1226
#define IDC_CSMGRID                     1227
#define IDC_STATIC_ETPROBEPROP          1228
#define IDC_BUTTON_BAKEENV              1229
#define IDC_BUTTON_BAKETRIS             1230
#define IDC_BUTTON_BAKETRIS2            1231
#define IDC_BUTTON_BAKEMINIMAP          1231
#define IDC_STATIC_SHOREWAVE            1232
#define IDC_BUTTON_BAKEOUTLINEMAP       1232
#define IDC_SLIDER2                     1233
#define IDC_SLIDER_SHAPEWOUTTER         1233
#define IDC_BUTTON_APPLYSHAPE           1234
#define IDC_BUTTON_APPLYBRUSH           1235
#define IDC_EDIT_SHAPEWINNER            1236
#define IDC_SLIDER__SHORE_STARTTIME     1237
#define IDC_STATIC_SHORECP              1238
#define IDC_STATIC_SHOREINFO            1242
#define IDC_BTN_SSCWATER                1243
#define IDC_BTN_SSCSHORE                1244
#define IDC_BTN_SSCFOREST               1245
#define IDC_BTN_SCCVEGTABLE             1246
#define IDC_EDITLIB                     1247
#define IDC_STATIC_SPTPROP              1248
#define IDC_FALLBACKSTATIC              1248
#define IDC_STATISTIC                   1249
#define IDC_BT_CHECKIN_KEEPOUT          1250
#define ID_EMPTY                        1251
#define IDC_EMPTY                       1251
#define IDC_BT_ASSIGNHMAP               1252
#define IDC_MTRLEXTANCHOR               1253
#define IDC_EDITOR                      1254
#define IDC_BROWSEMTENAME               1255
#define IDC_MTENAME                     1256
#define IDC_EDITEP                      1257
#define ID_BUTTON_CREATERIDGE           1258
#define ID_CHECK_CREATERIDGE            1258
#define IDC_LOD01                       1260
#define IDC_LOD1                        1260
#define IDC_LOD2                        1261
#define IDC_LOD3                        1262
#define IDC_LOD4                        1263
#define IDC_LOCATEERR                   1264
#define IDC_ERRSTR                      1265
#define ID_CHECK_CREATEROAD             1266
#define IDC_STATICPTOPS_ROAD            1267
#define IDC_RADIO_SPECIAL               1269
#define IDC_DOCUMENT                    1271
#define IDC_SPIN_CELLSIZE               1273
#define IDC_SPIN_CELLHEIGHT             1274
#define IDC_SPIN_AGENTHEIGHT            1275
#define IDC_SPIN_AGENTRADIUS            1276
#define IDC_SPIN_AGENTMAXCLIMB          1277
#define IDC_SPIN_AGENTMAXSLOPE          1278
#define IDC_SPIN_MINREGION              1279
#define IDC_SPIN_MERGEREGION            1280
#define IDC_SPIN_MAXEDGELEN             1281
#define IDC_SPIN_MAXEDGEERROR           1282
#define IDC_SPIN_VERPERPOLY             1283
#define IDC_SPIN_SAMPDIST               1284
#define IDC_SPIN_MAXSAMPERROR           1285
#define IDC_RADIO_STARTPOS              1286
#define IDC_RADIO_ENDPOS                1287
#define IDC_BUTTON_GENNAVMESH           1287
#define IDC_RADIO_BUILDNAVMESH          1288
#define IDC_RADIO4                      1289
#define IDC_RADIO_SELECTNAVMESH         1289
#define IDC_RADIO_OPADDATTR             1289
#define IDC_BUTTON_EXPORTNAVMESH        1290
#define IDC_RADIO_OPCLEARATTR           1290
#define IDC_RADIO_OPSETREGID            1291
#define IDC_RADIO_OPSELECTED            1292
#define IDC_LIST_MAPATTR                1296
#define IDC_STATIC_REGIDMAPATTR         1297
#define IDC_SPIN1                       1298
#define IDC_SPIN_OPMAPRANGE             1298
#define IDC_RADIO1                      1299
#define IDC_BUTTON_MAPATTREXPORT        1300
#define IDC_SOUNDANCHOR                 1301
#define IDC_PLAY                        1302
#define IDC_RECORD                      1303
#define IDC_SSNGRID                     1305
#define IDC_BGGRID                      1305
#define IDC_BGANCHOR                    1306
#define IDC_WORKINGFOLDER               2000
#define IDC_USER                        2001
#define IDC_PASSWORD                    2002
#define IDC_APPLY                       2004
#define IDC_PROJECTS                    2005
#define IDC_DATABASE                    2007
#define IDC_BROWSE                      2008
#define IDC_APPLYALL                    3001
#define IDC_LEAVE                       3002
#define IDC_REPLACE                     3003
#define IDD_RESOURCESELECTOR            4001
#define IDC_FILELIST                    4002
#define IDC_TEXTUREVIEWER               4003
#define IDC_COMBO_FILENAME              4004
#define IDC_COMBO_BRUSHTYPE             4004
#define IDC_COMBO_FILETYPE              4005
#define IDC_ROOTDIR                     4006
#define IDC_SEARCH                      4007
#define IDC_BT_CHECKIN                  4008
#define IDC_BUTTON_BAKE                 4009
#define IDC_BT_HEIGHTMAP                4010
#define IDC_ADDPROBE                    4011
#define IDC_COMBOLOD                    4012
#define IDC_COMBO_RANGE                 4013
#define IDC_COMBO_DENSITY               4014
#define IDC_COLOR_SET_SHOW              4015
#define IDC_RADIO_RGB_B                 4016
#define IDC_COLOR_SLIDER                4017
#define IDC_COLOR_SQUARE                4018
#define IDC_FINDINALL                   4019
#define IDC_MATCHCASE                   4020
#define IDC_MATCHWORD                   4021
#define IDC_EDIT_SEARCH				4040
#define IDD_DIALOG_FIND                 4022
#define IDC_FINDINPROTO                 4023
#define IDD_COLORALPHA_DLG              4023
#define IDD_ANIMTREEPANEL               4024
#define IDD_ANIMTREEPANEL1              4025
#define IDD_CSMPANEL                    4025
#define IDD_MFADLG1                     4026
#define IDD_CONFIGDLG                   4026
#define IDD_MTRLEXTMAIN                 4027
#define IDD_ACTOR_ROAD                  4028
#define IDD_EDITPANEL_ASSETLIB          4029
#define IDD_REFRESDLG                   4030
#define IDD_ACTOR_NAVMESH               4031
#define IDD_ACTOR_MAPATTR               4032
#define IDD_SOUNDPANEL                  4033
#define IDD_RECORDDLG                   4034
#define IDD_DIALOG_TOOLGAMERGN          4035
#define IDD_BEHAVIORGRAPHPANEL          4036
#define IDD_TRRNBRUSHSELDLG             4037
#define ID_BUTTON32771                  32771
#define ID_BUTTON32772                  32772
#define ID_SETTOOTPATH                  32772
#define ID_SETPATH                      32772
#define ID_PATHCOMBO                    32773
#define ID_SETFILEPATH                  32774
#define ID_SETFOLDERPATH                32780
#define ID_COMMON_DELETE                32790
#define ID_COMMON_COPY                  32791
#define ID_COMMON_CUT                   32792
#define ID_COMMON_PASTE                 32793
#define ID_COMMON_RENAME                32794
#define ID_CREATE_FOLDER                32795
#define ID_CREATE_FILE                  32796
#define ID_COMMON_ADD                   32798
#define ID_COMMON_REPLACE               32800
#define ID_COMMON_NEW                   32801
#define ID_OVERRIDEASSETCLASS           32901
#define ID_BUTTON32901                  32901
#define ID_BUTTONPLATPAUSE              32902
#define ID_BUTTONSTOP                   32903
#define ID_SSC_CHECKIN                  32904
#define ID_SSC_CHECKOUT                 32905
#define ID_SSC_GET                      32906
#define ID_SSC_ADDTOVSS                 32907
#define ID_SSC_RMFROMVSS                32908
#define ID_SSC_ADDFOLDER                32909
#define ID_SSC_REFRESH                  32910
#define ID_MENU_CHECKIN                 32911
#define ID_MENU_CHECKOUT                32912
#define ID_MENU_GET                     32913
#define ID_MENU_ADDTOVSS                32914
#define ID_MENU_RMFROMVSS               32915
#define ID_MENU_ADDFOLDER               32916
#define ID_MENU_REFRESH                 32917
#define ID_SSC_GETFOLDER                32918
#define ID_COMMON_NEW_START             32920
#define ID_COMMON_NEW_END               34920
#define ID_COMMON_MOVEUP                34921
#define ID_COMMON_MOVEDOWN              34922
#define ID_SSC_CHECKIN_KEEPOUT          34923
#define ID_MENU_CHECKIN_KEEPOUT         34924
#define ID_NODETREE_CUSTOM_START        35000
#define ID_NODETREE_CUSTOM_END          36000
#define ID_Menu36101                    36101
#define ID_RESTREE_COPYPATH             36102
#define ID_COMMON_REPLACE_NS            36103
#define ID_COMMON_REMOVE_NS             36104
#define ID_RESTREE_BROWSEFOLDER         36105
#define ID_FILTERCOMBO 36106

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1158
#define _APS_NEXT_COMMAND_VALUE         36107
#define _APS_NEXT_CONTROL_VALUE         1308
#define _APS_NEXT_SYMED_VALUE           4041
#endif
#endif
